---
- name: "HIGH | AIX7-00-003005 | AIX must disable /usr/bin/rcp, /usr/bin/rlogin, /usr/bin/rsh, /usr/bin/rexec and /usr/bin/telnet commands."
  block:
    - name: Check existence of r-command files
      ansible.builtin.stat:
        path: "{{ command_to_check }}"
      loop: "{{ files_to_check }}"
      loop_control:
        loop_var: command_to_check
      register: aix7_stig_rcommands_stat

    - name: Change permissions for r-commands that exist
      ansible.builtin.file:
        path: "{{ file_to_change }}"
        mode: "0000"
      loop: >-
        {{ aix7_stig_rcommands_stat.results
           | selectattr('stat.exists')
           | map(attribute='stat.path') }}
      loop_control:
        loop_var: file_to_change
  vars:
    files_to_check:
      - /usr/bin/rcp
      - /usr/bin/rlogin
      - /usr/bin/rsh
      - /usr/bin/rexec
      - /usr/bin/telnet
  when:
    - aix7_00_003005
  tags:
    - AIX7-00-003005
    - SV-101393
    - V-91295
    - CCI-000197
    - severity_high
