---
- name: "MEDIUM | AIX7-00-003063 | The ndpd-router must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/ndpd-router .*)$
    replace: '#\1'
  when:
    - aix7_00_003063
  tags:
    - AIX7-00-003063
    - V-91365
    - SV-101463
    - CCI-000381
    - severity_medium
