---
- name: "HIGH | AIX7-00-003022 | AIX must disable trivial file transfer protocol."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(tftp[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003022
  tags:
    - AIX7-00-003022
    - SV-101629
    - V-91531
    - CCI-001814
    - severity_high
