---
- name: "HIGH | AIX7-00-001137 | AIX must be able to control the ability of remote login for users."
  stephenulmer.aix.chsec:
    file: /etc/security/user
    stanza: default
    attrs:
      rlogin: 'false'
  when:
    - aix7_00_001137
  tags:
    - AIX7-00-001137
    - SV-101601
    - V-91503
    - CCI-002314
    - severity_high
