---
- name: "MEDIUM | AIX7-00-002077 | The inetd.conf file on AIX must be owned by root."
  ansible.builtin.file:
    path: /etc/inetd.conf
    owner: root
  notify: refresh inetd
  when:
    - aix7_00_002077
  tags:
    - AIX7-00-002077
    - V-91587
    - SV-101685
    - CCI-000366
    - severity_medium
