---
- name: "MEDIUM | AIX7-00-003016 | The AIX ldd command must be disabled."
  ansible.builtin.file:
    path: "/usr/bin/ldd"
    mode: "0000"
  when:
    - aix7_00_003016
  tags:
    - AIX7-00-003016
    - V-91619
    - SV-101717
    - CCI-000366
    - severity_medium
