---
- name: "MEDIUM | AIX7-00-002113 | The AIX SSH daemon must not allow compression."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?Compression (yes|no)'
    line: "Compression no"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002113
  tags:
    - AIX7-00-002113
    - SV-101803
    - V-91705
    - CCI-000366
    - severity_medium
