---
- name: "MEDIUM | AIX7-00-002141 | The AIX /etc/hosts file must be group-owned by root."
  ansible.builtin.file:
    path: "/etc/hosts"
    group: root
  when:
    - aix7_00_002141
  tags:
    - AIX7-00-002141
    - CCI-000366
    - severity_medium
