---
- name: "MEDIUM | AIX7-00-003062 | The ndpd-host daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/ndpd-host .*)$
    replace: '#\1'
  when:
    - aix7_00_003062
  tags:
    - AIX7-00-003062
    - SV-101461
    - V-91363
    - CCI-000381
    - severity_medium
