---
- name: "MEDIUM | AIX7-00-002123 | The AIX SSH daemon must not allow RhostsRSAAuthentication."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002123
  tags:
    - AIX7-00-002123
    - V-91749
    - SV-101847
    - CCI-000366
    - severity_medium