---
- name: "MEDIUM | AIX7-00-002104 | The AIX SSH server must use SSH Protocol 2."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?Protocol'
    line: "Protocol 2"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002104
  tags:
    - AIX7-00-002104
    - SV-101345
    - V-91245
    - CCI-000068
    - severity_medium
