---
- name: "MEDIUM | AIX7-00-003078 | The klogin daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(klogind[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003078
  tags:
    - AIX7-00-003078
    - V-91397
    - SV-101495
    - CCI-000381
    - severity_medium
