---
- name: "MEDIUM | AIX7-00-003056 | If rwhod is not required on AIX, the rwhod daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/rwhod .*)$
    replace: '#\1'
  when:
    - aix7_00_003056
  tags:
    - AIX7-00-003056
    - SV-101449
    - V-91351
    - CCI-000381
    - severity_medium
