---
- name: "MEDIUM | AIX7-00-003081 | The tftp daemon must be disabled on AIX."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_003081
  tags:
    - AIX7-00-003081
    - SV-101501
    - V-91403
    - CCI-000381
    - severity_medium