---
- name: "HIGH | AIX7-00-003070 | The ntalk daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(ntalk[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003070
  tags:
    - AIX7-00-003070
    - V-91379
    - SV-101477
    - CCI-000381
    - severity_high
