---
- name: "MEDIUM | AIX7-00-002072 | AIX system files, programs, and directories must be group-owned by a system group."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002072
  tags:
    - AIX7-00-002072
    - SV-101571
    - V-91473
    - CCI-001499
    - severity_medium