---
- name: "HIGH | AIX7-00-003101 | The AIX system must have no .netrc files on the system."
  block:
    - name: Search non-common file systems for .netrc files
      ansible.builtin.command:
        cmd: >-
          find /
              \(
              \(
              {% for fs in aix7_stig_nofind_file_systems + aix7_stig_common_file_systems %}
                -regex "^{{ fs }}" {{ "-o " if not loop.last else "" }}
              {% endfor %}
              \)
              -prune
              \)
              -o
              -name ".netrc"
              -print
      register: stig_aix7_find_netrc
      async: 3600
      poll: 30

    - name: Search common file systems for .netrc files
      ansible.builtin.command:
        cmd: >-
          find {{ aix7_stig_common_file_systems | join(' ') }}
              -name ".netrc"
              -type f
      register: stig_aix7_find_netrc_common
      when:
        - aix7_stig_common_file_systems | length > 0
        - aix7_stig_do_high_io
      run_once: yes
      async: 3600
      poll: 30

    - name: Print results
      debug:
        msg: "FINDING | AIX7-00-003101 | There is a .netrc file: {{ netrc_file }}"
      loop: >-
        {{ stig_aix7_find_netrc.stdout_lines
           + ( stig_aix7_find_netrc_common.stdout_lines
               | default([])
             )
        }}
      loop_control:
        loop_var: netrc_file
  become: yes
  when:
    - aix7_00_003101
  tags:
    - AIX7-00-003101
    - V-91289
    - SV-101387
    - CCI-000196
    - severity_high
