---
- name: "MEDIUM | AIX7-00-003088 | If Stream Control Transmission Protocol (SCTP) must be disabled on AIX."
  ansible.builtin.debug:
    msg: "FINDING | AIX7-00-003088 | bos.net.sctp should not be installed"
  when:
    - "'bos.net.sctp' in ansible_facts.filesets"
    - aix7_00_003088
  tags:
    - AIX7-00-003088
    - SV-101515
    - V-91417
    - CCI-000382
    - severity_medium
