---
- name: "MEDIUM | AIX7-00-003060 | If SNMP is not required on AIX, the snmpmibd daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/snmpmibd .*)$
    replace: '#\1'
  when:
    - aix7_00_003060
  tags:
    - AIX7-00-003060
    - SV-101457
    - V-91359
    - CCI-000381
    - severity_medium
