---
- name: "MEDIUM | AIX7-00-002110 | AIX must setup SSH daemon to disable revoked public keys."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?RevokedKeys'
    line: "RevokedKeys /etc/ssh/revoked_keys.txt"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002110
  tags:
    - AIX7-00-002110
    - V-91549
    - SV-101647
    - CCI-001991
    - severity_medium
