---
- name: "MEDIUM | AIX7-00-002115 | AIX must turn on SSH daemon reverse name checking."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?VerifyReverseMapping (yes|no)'
    line: "VerifyReverseMapping yes"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002115
  tags:
    - AIX7-00-002115
    - V-91727
    - SV-101825
    - CCI-000366
    - severity_medium
