---
- name: "MEDIUM | AIX7-00-002101 | AIX must monitor and record unsuccessful remote logins."
  block:
    - name: Check state of /etc/security/failedlogin
      ansible.builtin.stat:
        path: /etc/security/failedlogin
      register: aix7_stig_failedlogin_stat

    - name: Remove /etc/security/failedlogin if symbolic link
      ansible.builtin.file:
        path: /etc/security/failedlogin
        state: absent
      when:
        - aix7_stig_failedlogin_stat.stat.islink is defined
        - aix7_stig_failedlogin_stat.stat.islink
  when:
    - aix7_00_002101
  tags:
    - AIX7-00-002101
    - V-91241
    - SV-101341
    - CCI-000067
    - severity_medium
