---
- name: "HIGH | AIX7-00-001010 | The AIX SYSTEM attribute must not be set to NONE for any account."
  block:
    - name: Check AIX SYSTEM attribute for ALL users
      command:
        cmd: "lsuser -a SYSTEM ALL"
      changed_when: no
      register: stig_aix7_lsuser_system

    - name: Print results
      debug:
        msg: "FINDING | AIX7-00-001010 | User {{ item }} has attribute SYSTEM=NONE"
      loop: >-
        {{ stig_aix7_lsuser_system.stdout_lines
           | select('search', 'SYSTEM=NONE')
           | map('regex_replace', '^(\w+)', '\1') }}
  when:
    - aix7_00_001010
  tags:
    - AIX7-00-001010
    - V-91425
    - SV-101523
    - CCI-000764
    - severity_high
