---
- name: "HIGH | AIX7-00-002058 | The AIX rexec daemon must not be running."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(exec[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_002058
  tags:
    - AIX7-00-002058
    - V-91303
    - SV-101401
    - CCI-000197
    - severity_high
