---
- name: "MEDIUM | AIX7-00-003050 | If DHCP is not enabled in the network on AIX, the dhcprd daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/dhcprd .*)$
    replace: '#\1'
  when:
    - aix7_00_003050
  tags:
    - AIX7-00-003050
    - V-91337
    - SV-101435
    - CCI-000381
    - severity_medium
