---
- name: "MEDIUM | AIX7-00-002122 | The AIX SSH daemon must be configured to not use host-based authentication."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002122
  tags:
    - AIX7-00-002122
    - SV-101845
    - V-91747
    - CCI-000366
    - severity_medium