---
- name: "MEDIUM | AIX7-00-002145 | The AIX /etc/syslog.conf file must be group-owned by root."
  ansible.builtin.file:
    path: "/etc/syslog.conf"
    group: root
  when:
    - aix7_00_002145
  tags:
    - AIX7-00-002145
    - CCI-000366
    - severity_medium
