---
- name: "MEDIUM | AIX7-00-003099 | AIX must allow admins to send a message to a user who logged in currently."
  block:
    - name: The /usr/bin/write command should exist
      ansible.builtin.stat:
        path: /usr/bin/write
      register: aix7_stig_write_stat

    - name: The /usr/bin/write command does not exist
      ansible.builtin.debug:
        msg: "FINDING | AIX7-00-003099 | The /usr/bin/write command is missing"
      when: not aix7_stig_write_stat.stat.exists
  when:
    - aix7_00_003099
  tags:
    - AIX7-00-003099
    - V-91507
    - SV-101605
    - CCI-002165
    - severity_medium
