---
- name: "MEDIUM | AIX7-00-002144 | The AIX /etc/syslog.conf file must be owned by root."
  ansible.builtin.file:
    path: "/etc/syslog.conf"
    owner: root
  when:
    - aix7_00_002144
  tags:
    - AIX7-00-002144
    - CCI-000366
    - severity_medium
