---
- name: "MEDIUM | AIX7-00-003048 | If SNMP is not required on AIX, the snmpd service must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/snmpd .*)$
    replace: '#\1'
  when:
    - aix7_00_003048
  tags:
    - AIX7-00-003048
    - SV-101431
    - V-91333
    - CCI-000381
    - severity_medium
