---
- name: "MEDIUM | AIX7-00-002083 | The AIX /etc/group file must be owned by root."
  ansible.builtin.file:
    path: "/etc/group"
    owner: root
  when:
    - aix7_00_002083
  tags:
    - AIX7-00-002083
    - SV-101709
    - V-91611
    - CCI-000366
    - severity_medium
