---
- name: "MEDIUM | AIX7-00-003057 | The timed daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/timed .*)$
    replace: '#\1'
  when:
    - aix7_00_003057
  tags:
    - AIX7-00-003057
    - SV-101451
    - V-91353
    - CCI-000381
    - severity_medium
