---
- name: "MEDIUM | AIX7-00-001039 | The AIX root accounts home directory (other than /) must have mode 0700."
  ansible.builtin.file:
    path: ansible_env.HOME
    mode: '0700'
    state: directory
  when:
    - aix7_00_001039
    - ansible_env.HOME != '/'
  tags:
    - AIX7-00-001039
    - V-91753
    - SV-101851
    - CCI-000366
    - severity_medium
