---
- name: "MEDIUM | AIX7-00-001132 | AIX must prevent the use of dictionary words for passwords."
  stephenulmer.aix.chsec:
    file: /etc/security/user
    stanza: default
    attrs:
      dictionlist: "/etc/security/ice/dictionary/English"
    state: present
  when:
    - aix7_00_001132
  tags:
    - AIX7-00-001132
    - V-91567
    - SV-101665
    - CCI-000366
    - severity_medium
