---
- name: "MEDIUM | AIX7-00-002140 | The AIX /etc/hosts file must be owned by root."
  ansible.builtin.file:
    path: "/etc/hosts"
    owner: root
  when:
    - aix7_00_002140
  tags:
    - AIX7-00-002140
    - CCI-000366
    - severity_medium
