---
- name: "MEDIUM | AIX7-00-002089 | Samba packages must be removed from AIX."
  ansible.builtin.debug:
    msg: "FINDING | AIX7-00-002089 | Samba packages are installed"
  when:
    - ansible_facts.filesets | select('search', 'samba') | length > 0
    - aix7_00_002089
  tags:
    - AIX7-00-002089
    - SV-101669
    - V-91571
    - CCI-000366
    - severity_medium
