---
- name: "MEDIUM | AIX7-00-002064 | IP forwarding for IPv4 must not be enabled on AIX unless the system is a router."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002064
  tags:
    - AIX7-00-002064
    - V-91681
    - SV-101779
    - CCI-000366
    - severity_medium