---
- name: "MEDIUM | AIX7-00-001000 | AIX /etc/security/mkuser.sys.custom file must not exist unless it is needed for customizing a new user account."
  ansible.builtin.file:
    path: "/etc/security/mkuser.sys.custom"
    state: absent
  when:
    - aix7_00_001000
  tags:
    - AIX7-00-001000
    - SV-101313
    - V-91213
    - CCI-000015
    - severity_medium
