---
- name: "HIGH | AIX7-00-002060 | AIX ftpd daemon must not be running."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(ftp[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_002060
  tags:
    - AIX7-00-002060
    - V-91307
    - SV-101405
    - CCI-000197
    - severity_high
