---
- name: "MEDIUM | AIX7-00-003071 | The chargen daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(chargen[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003071
  tags:
    - AIX7-00-003071
    - SV-101479
    - V-91381
    - CCI-000381
    - severity_medium
