---
- name: "MEDIUM | AIX7-00-003079 | The kshell daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(kshell[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003079
  tags:
    - AIX7-00-003079
    - SV-101497
    - V-91399
    - CCI-000381
    - severity_medium
