---
- name: "MEDIUM | AIX7-00-002150 | AIX cron and crontab directories must be group owned by cron."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002150
  tags:
    - AIX7-00-002150
    - CCI-000366
    - severity_medium