---
- name: "HIGH | AIX7-00-001008 | All accounts on AIX system must have unique account names."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_001008
  tags:
    - AIX7-00-001008
    - SV-101519
    - V-91421
    - CCI-000764
    - severity_high