---
- name: "MEDIUM | AIX7-00-002116 | AIX SSH daemon must perform strict mode checking of home directory configuration files."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?StrictModes (yes|no)'
    line: "StrictModes yes"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002116
  tags:
    - AIX7-00-002116
    - SV-101827
    - V-91729
    - CCI-000366
    - severity_medium
