---
- name: "MEDIUM | AIX7-00-003055 | If AIX server is not functioning as a network router, the routed daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/routed .*)$
    replace: '#\1'
  when:
    - aix7_00_003055
  tags:
    - AIX7-00-003055
    - V-91349
    - SV-101447
    - CCI-000381
    - severity_medium
