---
- name: "MEDIUM | AIX7-00-002146 | The AIX /etc/syslog.conf file must have a mode of 0640 or less permissive."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002146
  tags:
    - AIX7-00-002146
    - CCI-000366
    - severity_medium