---
- name: "MEDIUM | AIX7-00-003067 | The uucp (UNIX to UNIX Copy Program) daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(uucp[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003067
  tags:
    - AIX7-00-003067
    - V-91373
    - SV-101471
    - CCI-000381
    - severity_medium
