---
- name: "MEDIUM | AIX7-00-002096 | AIX must encrypt user data at rest using AIX Encrypted File System (EFS) if it is required."
  block:
    - name: clic.rte fileset message
      ansible.builtin.debug:
        msg: "FINDING | AIX7-00-002096 | clic.rte.{lib,kernext} fileset is not installed"
      when: ('clic.rte.lib' not in ansible_facts.filesets) or
            ('clic.rte.kernext' not in ansible_facts.filesets)

    - name: Unimplemented check
      ansible.builtin.debug:
        msg: "UNIMPLEMENTED: Check list of non-default filesystems for JFS2 encryption"
  when:
    - aix7_00_002096
  tags:
    - AIX7-00-002096
    - V-91723
    - SV-101821
    - CCI-000366
    - CCI-002475
    - CCI-002476
    - severity_medium
