---
- name: "MEDIUM | AIX7-00-002117 | AIX must turn off X11 forwarding for the SSH daemon."
  ansible.builtin.lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: '^(# *)?X11Forwarding (yes|no)'
    line: "X11Forwarding no"
    state: present
    validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002117
  tags:
    - AIX7-00-002117
    - V-91731
    - SV-101829
    - CCI-000366
    - severity_medium
