---
- name: "MEDIUM | AIX7-00-003053 | If AIX server is not functioning as a multicast router, the mrouted daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/rc.tcpip
    regexp: ^(start /usr/sbin/mrouted .*)$
    replace: '#\1'
  when:
    - aix7_00_003053
  tags:
    - AIX7-00-003053
    - SV-101443
    - V-91345
    - CCI-000381
    - severity_medium
