---
- name: "MEDIUM | AIX7-00-002142 | The AIX /etc/hosts file must have a mode of 0640 or less permissive."
  ansible.builtin.file:
    path: "/etc/hosts"
    mode: "0640"
  when:
    - aix7_00_002142
  tags:
    - AIX7-00-002142
    - CCI-000366
    - severity_medium
