---
- name: "HIGH | AIX7-00-001008 | All accounts on AIX system must have unique account names."
  block:
    - name: Run AIX usrck Command
      ansible.builtin.command:
        cmd: "usrck -n ALL"
      changed_when: no
      failed_when: no
      register: aix7_stig_usrck_names

    - name: Print usrck results
      debug:
        msg: "FINDING | AIX7-00-001008 | There are AIX accounts with duplicate names."
      when: aix7_stig_usrck_names.stdout is search('user name \w+ is not unique')
  when:
    - aix7_00_001008
  tags:
    - AIX7-00-001008
    - SV-101519
    - V-91421
    - CCI-000764
    - severity_high
