---
- name: "HIGH | AIX7-00-003040 | The AIX rsh daemon must be disabled."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(shell[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003040
  tags:
    - AIX7-00-003040
    - SV-101397
    - V-91299
    - CCI-000197
    - severity_high
