---
- name: "HIGH | AIX7-00-003041 | The AIX rlogind service must be disabled."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(login[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003041
  tags:
    - AIX7-00-003041
    - V-91301
    - SV-101399
    - CCI-000197
    - severity_high
