---
- name: "MEDIUM | AIX7-00-002078 | AIX cron and crontab directories must be owned by root or bin."
  ansible.builtin.file:
    path: "/var/spool/cron/crontabs"
    owner: bin # or root
    state: directory
  when:
    - aix7_00_002078
  tags:
    - AIX7-00-002078
    - V-91595
    - SV-101693
    - CCI-000366
    - severity_medium
