---
- name: "MEDIUM | AIX7-00-002105 | AIX must config the SSH idle timeout interval."
  block:
    - name: Ensure ClientAliveInterval is set in /etc/ssh/sshd_config
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^(# *)?ClientAliveInterval'
        line: "ClientAliveInterval 600"
        state: present
        validate: "/usr/sbin/sshd -t -f %s"

    - name: Ensure ClientAliveCountMax is set in /etc/ssh/sshd_config
      ansible.builtin.lineinfile:
        path: "/etc/ssh/sshd_config"
        regexp: '^(# *)?ClientAliveCountMax'
        line: "ClientAliveCountMax 0"
        state: present
        validate: "/usr/sbin/sshd -t -f %s"
  notify: restart sshd
  when:
    - aix7_00_002105
  tags:
    - AIX7-00-002105
    - V-91491
    - SV-101589
    - CCI-001133
    - CCI-002361
    - severity_medium
