---
- name: "MEDIUM | AIX7-00-003082 | The imap2 service must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(imap2[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003082
  tags:
    - AIX7-00-003082
    - V-91405
    - SV-101503
    - CCI-000381
    - severity_medium
