---
- name: "MEDIUM | AIX7-00-003067 | The uucp (UNIX to UNIX Copy Program) daemon must be disabled on AIX."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_003067
  tags:
    - AIX7-00-003067
    - V-91373
    - SV-101471
    - CCI-000381
    - severity_medium