---
- name: "MEDIUM | AIX7-00-003086 | The echo daemon must be disabled on AIX."
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: ^(echo[ \t]+.*)$
    replace: '#\1'
  notify: refresh inetd
  when:
    - aix7_00_003086
  tags:
    - AIX7-00-003086
    - SV-101511
    - V-91413
    - CCI-000381
    - severity_medium
