---
- name: "MEDIUM | AIX7-00-002084 | The AIX /etc/group file must be group-owned by security."
  ansible.builtin.file:
    path: "/etc/group"
    group: security
  when:
    - aix7_00_002084
  tags:
    - AIX7-00-002084
    - SV-101711
    - V-91613
    - CCI-000366
    - severity_medium
