# Copyright (c) 2022 Stephen L. Ulmer

namespace: stephenulmer
name: aix
version: 0.0.9
readme: README.md

authors:
- Stephen L. Ulmer <ulmer@ulmer.org>

description: Ansible Content for Security Technical Implementation Guide (STIG) Controls for AIX

license:
- MIT

tags:
  - aix
  - compliance
  - hardening
  - infrastructure
  - power
  - security
  - stig
  - system

dependencies:
  ibm.power_aix: "*"

repository: https://github.com/stephenulmer/ansible-aix-collection
issues: https://github.com/stephenulmer/ansible-aix-collection/issues

build_ignore:
- etc/
- '*.tar.gz'
