---
- name: "MEDIUM | AIX7-00-002091 | The AIX /etc/group file must have mode 0644 or less permissive."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002091
  tags:
    - AIX7-00-002091
    - SV-101713
    - V-91615
    - CCI-000366
    - severity_medium