---
- name: "MEDIUM | AIX7-00-003060 | If SNMP is not required on AIX, the snmpmibd daemon must be disabled."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_003060
  tags:
    - AIX7-00-003060
    - SV-101457
    - V-91359
    - CCI-000381
    - severity_medium