---
- name: "MEDIUM | AIX7-00-002121 | The AIX SSH daemon must be configured to disable user .rhosts files."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002121
  tags:
    - AIX7-00-002121
    - SV-101843
    - V-91745
    - CCI-000366
    - severity_medium