---
- name: "MEDIUM | AIX7-00-002200 | The AIX audit configuration files must be owned by root."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002200
  tags:
    - AIX7-00-002200
    - SV-101369
    - V-91271
    - CCI-000171
    - severity_medium