---
- name: "MEDIUM | AIX7-00-003085 | The instsrv daemon must be disabled on AIX."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_003085
  tags:
    - AIX7-00-003085
    - V-91411
    - SV-101509
    - CCI-000381
    - severity_medium