---
- name: "MEDIUM | AIX7-00-002148 | The AIX /var/spool/cron/atjobs directory must be group-owned by daemon."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002148
  tags:
    - AIX7-00-002148
    - CCI-000366
    - severity_medium