---
- name: "MEDIUM | AIX7-00-003069 | The talk daemon must be disabled on AIX."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_003069
  tags:
    - AIX7-00-003069
    - SV-101475
    - V-91377
    - CCI-000381
    - severity_medium