---
- name: "HIGH | AIX7-00-001009 | All accounts on AIX must be assigned unique User Identification Numbers (UIDs) and must authenticate organizational and non-organizational users (or processes acting on behalf of these users)."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_001009
  tags:
    - AIX7-00-001009
    - V-91423
    - SV-101521
    - CCI-000764
    - CCI-000804
    - severity_high