---
- name: "MEDIUM | AIX7-00-002120 | The AIX SSH daemon must be configured to disable empty passwords."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002120
  tags:
    - AIX7-00-002120
    - V-91743
    - SV-101841
    - CCI-000366
    - severity_medium