---
- name: "MEDIUM | AIX7-00-002100 | AIX must monitor and record successful remote logins."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_002100
  tags:
    - AIX7-00-002100
    - V-91239
    - SV-101339
    - CCI-000067
    - severity_medium