---
- name: "MEDIUM | AIX7-00-001042 | The Department of Defense (DoD) login banner must be displayed immediately prior to, or as part of, graphical desktop environment login prompts on AIX."
  debug: msg="CONTROL NOT IMPLEMENTED"
  when:
    - aix7_00_001042
  tags:
    - AIX7-00-001042
    - V-91223
    - SV-101323
    - CCI-000048
    - severity_medium